insert into employee (FirstName, LastName, Phone_cell, phone_cell_publish, Email, DOB) values
  ('Tommy','Morish','5856940947', 'true', '', Null),
  ('Harold','Clark','5855124786','True','thetreerat@gmail.com', '12/24/1969'),
  ('Alex','Consentine','3157378948','True','', Null),
  ('Anthony','Mangieri','5856452421','True','', Null),
  ('Chris','Bills','5855207590','True','', Null),
  ('Murphy','Swain','5857977301','True','', Null),
  ('Tyler','Austin','5857545824','True','', Null),
  ('Zach','Shultz','3155211883','True','', Null),
  ('Guy','Boor','','False','', Null),
  ('Lee','Dame','','False','', Null),
  ('Jim', 'Morsch','','False','', Null),
  ('Nick','Alfano','','False','', Null),
  ('Nickolas','Brown','','False','', Null),
  ('Ben','Couture','','False','', Null),
  ('Noah','Crichlow','','False','', Null),
  ('John','Crowley','','False','', Null),
  ('Kiernan','Crowley','','False','', Null),
  ('Sydney','Diberardinis','','False','',Null),
  ('Frank','Heirermann','','False','',Null),
  ('Joshua','Pike','','False','',Null),
  ('Lauren','Pilletteri','','False','',Null),
  ('Jon','Russell','','False','',Null),
  ('Joseph','Scardilla','','False','',Null),
  ('Jesse','Sheets','','False','',Null),
  ('Luke','Sheets','','False','',Null),
  ('Zachary','Shultz','','False','',Null),
  ('Jacob','Slocuk','','False','',Null),
  ('Devon','Spychalski','','False','',Null),
  ('Anthony','Stirpe','','False','',Null),
  ('James','Vennette','','False','',Null),
  ('Brendon','Vize','','False','',Null),
  ('Andrew','Walsh','','False','',Null),
  ('Dayton','Wilson','','False','',Null),
  ('Cody','Wolschlegal','','False','',Null),
  ('Andrew','Baker','','False','',Null);
  
  insert into shift_templates (Shift_Name, Start_Name, End_Time, DOW) values
  ('Park Night 1','3:30 pm','8:30 pm','monday'),
  ('Park Night 2','3:30 pm','8:30 pm','monday'),
  ('Park Night 3','5:00 pm','8:00 pm','monday'),
  ('Park Night 1','3:30 pm','8:30 pm','tuesday'),
  ('Park Night 2','3:30 pm','8:30 pm','tuesday'),
  ('Park Night 2','5:00 pm','8:00 pm','tuesday'),
  ('Park Night 1','3:30 pm','8:30 pm','wednesday'),
  ('Park Night 2','3:30 pm','8:30 pm','wednesday'),
  ('Park Night 3','5:00 pm','8:00 pm','wednesday'),
  ('Park Night 1','3:30 pm','8:30 pm','thursday'),
  ('Park Night 2','3:30 pm','8:30 pm','thursday'),
  ('Park Night 3','5:00 pm','8:00 pm','thursday'),
  ('Park Night 1','3:30 pm','8:30 pm','friday'),
  ('Park Night 2','3:30 pm','8:30 pm','friday'),
  ('Park Night 3','5:00 pm','8:00 pm','friday'),
  ('Park Night 3','5:00 pm','8:00 pm','friday'),
  ('Park Night 1','3:30 pm','8:30 pm','saturday'),
  ('Park Night 2','3:30 pm','8:30 pm','saturday'),
  ('Park Night 3','5:00 pm','8:00 pm','saturday'),
  ('Park Night 1','3:30 pm','8:30 pm','sunday'),
  ('Park Night 2','3:30 pm','8:30 pm','sunday'),
  ('Park Night 3','5:00 pm','8:00 pm','sunday'),
  ('Brigade SB 1', '10:00', '3:00', 'saturday'),
  ('Brigade SB 2', '10:00', '3:00', 'saturday'),
  ('Brigade SB 3', '10:00', '3:00', 'saturday'),
  ('Park Runners SB 1', '10:00', '3:00', 'saturday'),
  ('Mountain Runners SB 1', '10:00', '3:00', 'saturday'),
  ('SB Lineup Sup','4:00 pm','7:00 pm','monday'),
  ('SB Lineup Sup','4:00 pm','7:00 pm','tuesday'),
  ('SB Lineup Sup','4:00 pm','7:00 pm','wednesday'),
  ('SB Lineup Sup','4:00 pm','7:00 pm','thursday'),
  ('SB Lineup Sup','4:00 pm','7:00 pm','friday'),
  ('SB Lineup Sup','4:00 pm','5:00 pm','saturday');

insert into Cert_Template (Title, Org) values
  ('AASI Level 1','AASI'),
  ('AASI Level 2','AASI'),
  ('AASI Level 3','AASI'),
  ('PSIA Level 1','PSIA'),
  ('PSIA Level 2','PSIA'),
  ('PSIA Level 3','PSIA'),
  ('Frestyle Level 1','AASI'),
  ('Frestyle Level 2','AASI'),
  ('Childern Level 1','PSIA'),
  ('Childern Level 2','PSIA'),
  ('Level 1 SB', 'Bristol'),
  ('Level 2 SB', 'Bristol'),
  ('Level 3 SB', 'Bristol'),
  ('Level 1 Ski', 'Bristol'),
  ('Level 2 Ski', 'Bristol'),
  ('Level 3 Ski', 'Bristol'),
  ('Park 1','Bristol'),
  ('Park Lead','Bristol'),
  ('Park Sup', 'Bristol'),
  ('Ski Lineup Sup', 'Bristol'),
  ('SB Lineup Sup', 'Bristol'),
  ('Park Manager','Bristol')
  ('Instructor Training', 'Bristol'),
  ('Mentor Program Training', 'Bristol'),
  ('Mentor','Bristol');
